from typing import Protocol
from uuid import UUID

from backend.domain.recipe import Recipe


class RecipeRepository(Protocol):
    def list_recipes(self) -> list[Recipe]: ...

    def find_by_id(self, recette_id: UUID) -> Recipe | None: ...

    def add_recipe(self, recette: Recipe) -> Recipe: ...

    def update_recipe(self, recette: Recipe) -> None: ...

    def delete_recipe(self, recette_id: UUID) -> None: ...
