from typing import Protocol
from uuid import UUID

from backend.domain.recipe import Recipe, NewRecipe
from backend.domain.ingredient import Ingredient, NewIngredient
from backend.domain.measured_ingredients import RecipeIngredient


class RecipeRepository(Protocol):
    def list_recipes(self) -> list[Recipe]: ...

    def find_by_id(self, recipe_id: UUID) -> Recipe | None: ...

    def add_recipe(self, new_recipe: NewRecipe) -> Recipe: ...

    def update_recipe(self, recipe: Recipe) -> None: ...

    def delete_recipe(self, recipe_id: UUID) -> None: ...

class IngredientRepository(Protocol):
    def list_ingredients(self) -> list[Ingredient]: ...

    def find_by_id(self, ingredient_id: UUID) -> Ingredient | None: ...

    def add_ingredient(self, new_ingredient: NewIngredient) -> Ingredient: ...

    def update_ingredient(self, ingredient: Ingredient) -> None: ...

    def delete_ingredient(self, ingredient_id: UUID) -> None: ...

class RecipeIngredientRepository(Protocol):
    def get_ingredients_of_recipe(self, recipe_id: UUID) -> list[RecipeIngredient]: ...

    def add_recipe_ingredient(self, recipe_id: UUID, recipe_ingredient: RecipeIngredient,) -> None: ...

    def update_recipe_ingredients(self, recipe_id: UUID, recipe_ingredients: list[RecipeIngredient]) -> None: ...

    def delete_recipe_ingredient(self, recipe_id: UUID, ingredient_id: UUID) -> None: ...

    def delete_all_recipe_ingredients_for_recipe(self, recipe_id: UUID) -> None: ...